### ISSUE TITLE
Weather Unlocked site dead? 

### ISSUE THREAD

**Issue by LissieTilbrook** [MetalChris/repository.metalchris#26]
I tried to get an API key but no response from these people. Usually sign up confirmation emails are sent almost immediately. I signed up an hour ago and nothing. Not in my spam, not in inbox.

I even tried reaching out for support. Ignored. No response yet.

Last Facebook and Google+ posts by them were in 2015. Their Twitter has no tweets. Last blog post on their site was 2015.

For what it's worth, this site, weatherunlocked.com, is dead.

**Comment by MetalChris** [comment]
Sorry you're having trouble with the site.  I get regular emails from Weather Unlocked regarding API usage, changes and updates, as well as new offerings.  Other than an occasional instance, the add-on works fine for me, and has been downloaded several hundred times without any complaints.  Again, I'm sorry you're having trouble with the website, but since this is not an issue with the add-on, I'm going to close this.
