### ISSUE TITLE
Reuters

### ISSUE THREAD

**Issue by GoatSniper** [MetalChris/repository.metalchris#45]
Top Stories and Categories seemed to have stopped working though Live Streams still do, Thanks in advance

**Comment by MetalChris** [comment]
Website changes.  Give me a couple of days and I should have an updated version available.

**Comment by MetalChris** [comment]
Just uploaded and updated version.  Top Stories is working again.  I've replaced Categories with Featured because the Categories do not seem to work properly on the website.  No matter which video you try to view, it seems to give you the Top Stories.  The Featured section has longer in depth stories on one particular topic.  Try version 2018.12.08 and let me know if it works for you.

**Comment by GoatSniper** [comment]
Thank you, Everything seems to be working fine

**Comment by MetalChris** [comment]
Cool!  Thanks for the feedback, I'll go ahead and close this issue.
