### ISSUE TITLE
CW plugin

### ISSUE THREAD

**Issue by Vijaye82** [MetalChris/repository.metalchris#48]
Hi 

I found your CW TV plugin and installed it and found that it it pauses ever 20secs of the stream before it starts again. When i stream off my laptop it seems to work fine, 
I've twerked the kodi buffer settings and this hasnt resolved it, so just wanted to know if it was just me that had experienced this?

Sorry PM'd you on the kodi forum too.

**Comment by MetalChris** [comment]
What OS and what version of Kodi are you using?  I've been watching for over 15 minutes and have seen no buffering at all.  Please upload a log to pastebin.com or similar site and provide a link.

**Comment by Vijaye82** [comment]
Hi

Im an amazon firetv 4k (the square box version) using Kodi 18

link to log:
https://paste.kodi.tv/tapameliqu

Probably mention im in the UK and use a VPN, but i dont seem to have a problem using the VPN on my laptop to stream.

Thanks for looking into this

**Comment by MetalChris** [comment]
First, I don't believe you have an officially supported version of Kodi on your device, and I see at least six banned add-ons or repositories on your system.  Ares, Covenant, Exodus, Kodibae, Schism, and Smoothstreams are all banned not only because they offer access to pirated content, but also because some or all of them can cause performance issues.  I'd suggest checking the list of banned addons and repositories on the Kodi.tv website and removing those and see if your problems continue.  Install an officially supported version of Kodi from either the Kodi.tv website or from the Play store.  If you are using a wireless connection, I'd suggest switching to a wired connection as wireless speeds can fluctuate wildly, and can cause performance issues.  Beyond that, not all VPN's are created equal.  I haven't used one in some time, but I did have to try a few before I found one that worked for my purposes.  Also, the add-on and website don't present the same stream.  While the website provides access to a multi-bitrate hls stream, the add-on only provides the highest available bitrate (1080 @ 8000k) stream.  This, combined with your use of a VPN, and all the banned add-ons, could be what is causing the buffering you're experiencing.  Confirm you are actually able to stream at 1080 via the website to verify the VPN supports the required high bandwidth.  Try the other suggestions above and if you are still having the same issues, please post a link to a new log and I'll look into it further.

**Comment by Vijaye82** [comment]
Hi, thanks for looking into this.. i will try what out what you have mentioned and see how that goes.

**Comment by MetalChris** [comment]
No response in over a month, so I'm closing this one.
