### ISSUE TITLE
[request] dark sky weather

### ISSUE THREAD

**Issue by mgonzales71** [MetalChris/repository.metalchris#50]
First thanks for the dark sky addon - very much appreciated.

Just a couple requests for consideration as possible future dark sky addon updates..

1)  Any chance to use script.openweathermap.maps to provide weather maps with this addon?  I figure that would require a setting for the free API key for that service but it would be a welcome feature if doable.

2) Weather Underground was the last weather addons that supported weather alerts (or have I missed that any other addons provide for this?).  The Dark Sky API supports this as does Kodi if provided by the addon.

WU Code for weather alerts:

```
# alert properties
    set_property('Alerts.IsFetched', 'true')
    if str(data['alerts']) != '[]':
        rss = ''
        alerts = ''
        for count, item in enumerate(data['alerts']):
            description = recode(item['description']) # workaround: wunderground provides a corrupt alerts message
            message = recode(item['message']) # workaround: wunderground provides a corrupt alerts message
            set_property('Alerts.%i.Description'     % (count+1), description)
            set_property('Alerts.%i.Message'         % (count+1), message)
            set_property('Alerts.%i.StartDate'       % (count+1), item['date'])
            set_property('Alerts.%i.EndDate'         % (count+1), item['expires'])
            set_property('Alerts.%i.Significance'    % (count+1), SEVERITY[item['significance']])
            rss    = rss + description.replace('\n','') + ' - '
            alerts = alerts + message + '[CR][CR]'
        set_property('Alerts.RSS'   , rss.rstrip(' - '))
        set_property('Alerts'       , alerts.rstrip('[CR][CR]'))
        set_property('Alerts.Count' , str(count+1))
    else:
        set_property('Alerts.RSS'   , '')
        set_property('Alerts'       , '')
        set_property('Alerts.Count' , '0')
```

Again thanks for the addon and consideration of this request.

Mario

**Comment by mgonzales71** [comment]
another weather addon idea that also provides weather alerts as well:

https://forecast-v3.weather.gov/documentation
https://www.weather.gov/documentation/services-web-api

again thanks for the consideration and your work on dark sky 👍

**Comment by MetalChris** [comment]
Thanks for the feedback and suggestions.  Nice to know people find my add-ons useful.  This add-on and my Weather Unlocked add-on are both basically hacks of an old version of Ronie's Yahoo Weather add-on.  I originally tried working with the weather.gov API, but because of the way the info was provided (by 12 hour periods rather than by day) I had difficulty getting the high and low temps to display correctly.  I did try at one time to create a stand alone weather alerts service with their API, but got busy with other stuff and abandoned it.  I am using the Dark Sky API for the [weather page](http://weather.the-antinet.net/local/) on my website, and it does display the provided alerts when any are active.  I didn't even think to use this feature in the add-on.  If I can find the time, I may look into adding these to the Dark Sky add-on.  Maps are another story.  Dark Sky also provides maps, but not through their API, and I'm not familiar at all with script.openweathermaps.maps, so I'd have to move into 'uncharted territory' to do this.  It would be a useful feature to add though, but time constraints would likely keep this low on my to do list.  Thanks again for the feedback and suggestions.

**Comment by mgonzales71** [comment]
You’re welcome and the open weather maps scripts is a separate from the weather addon for open weather so should be able to import and use it with your addon just may need to have a place to allow users to provide api key for dark sky and open weather as well 

Thanks again for the addon and consideration 

Also if you search GitHub there are a few repos of python code that already work with APIs of weather.gov, dark sky, etc
